### ISSUE TITLE
Option to record all active tracks when visible_tracks = True

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#109]
We would like to be able to configure our CAs to record all tracks that are configured active, regardless of the capture.device.names list sent by the core for a specific recording.

Setting visible_tracks = false would achieve this, but we still want Galicaster to report its active tracks to the core for monitoring and management purposes.

**Comment by hcaloto** [comment]
Stephen, what's the specific use case for this? Can you describe it for us?

**Comment by hcaloto** [comment]
Hi @smarquard, 

I'm going to close this issue because Galicaster does not use the parameter "active" since 1.2 (approximately). If you are still interested in this feature please let us know it and in that case we should include an extra parameter in the Opencast section in order to ignore capture.device.names.

Best regards
