### ISSUE TITLE
Profiles do not work: invalid track type

### ISSUE THREAD

**Issue by svnset** [teltek/Galicaster#211]
The profiles are not working anymore, I get the message: "invalid track type... for ...  track: gst_parse_error: no bin "bin" 

I guess it is related to the line:
`bin = Gst.parse_launch("( {} )".format(aux))`
If i comment the line and use the one above: 
`bin = Gst.parse_bin_from_description(aux, False)`
everything works again except for the blackmagic card which seems not to work at all in ubuntu 16.04.

galicaster.log attached

**Comment by bleedinge** [comment]
Could you please provide:

- The commit you tested this with
- The profile you used
- The logfile for this error

Thanks!

**Comment by hcaloto** [comment]
We have just found an error when replacing the audio sinks for Blackmagic and RTP devices, so now this issue should not happen

https://github.com/teltek/Galicaster/commit/0d081abfae2888d2a29fd1a168b7ba53d2572130

**Comment by rubenrua** [comment]
Could you execute in a terminal:

```
gst-inspect-1.0 bin
```

**Comment by sinhote** [comment]
Hi,

Just a quick reminder that this is still happening for us. Robin can reproduce the issue while I cannot, so this is not reproducible the 100% of the times. The error is: 

> Invalid track type "rtp" for "RTP Camera" track: gst_parse_error: Kein Behälter »Behälter« - Elemente werden entpackt (1)

, which is basically the same error described aboved, but in German.

The workaround of using "parse_bin_from_description" instead of "parse_launch" still works, but it is annoying that we have to modify the source code.

Any ideas?

**Comment by Alfro** [comment]
@sinhote We can't reproduce this bug. Do you still have this problem?

**Comment by sinhote** [comment]
Hi @Alfro,

We discovered that it only happens when the system language is German. (!!!) I totally forgot to comment on here. 

This is clearly an upstream bug and should be reported upstream. 

Thanks!
