### ISSUE TITLE
gst-resource-error-quark: Failed to allocate a buffer

### ISSUE THREAD

**Issue by smarquard** [teltek/Galicaster#366]
This happens intermittently with the Datapath E2S card

Galicaster is idle:

```
galicaster      2016-07-21 11:45:56,588 ERROR   recorder/recorder       gst-resource-error-quark: Failed to allocate a buffer (14) (gstv4l2src.c(851): gst_v4l2src_create (): /GstPipeline:galicaster_recorder/galicaster+recorder+bins+v4l2+GCv4l2:galicaster+recorder+bins+v4l2+gcv4l2-2/GstBin:bin4/GstV4l2Src:gc-v4l2-src)
galicaster      2016-07-21 11:45:56,731 ERROR   recorder/service        Handle error (gst-resource-error-quark: Failed to allocate a buffer (14) (gstv4l2src.c(851): gst_v4l2src_create (): /GstPipeline:galicaster_recorder/galicaster+recorder+bins+v4l2+GCv4l2:galicaster+recorder+bins+v4l2+gcv4l2-2/GstBin:bin4/GstV4l2Src:gc-v4l2-src))
```

Appears to be correlated with these entries from /var/log/syslog:

```
/var/log/syslog:

Jul 21 11:45:55 em7-ca kernel: [18944.845683] <6>rgb133: DetectMode: NoVideo for dev[1].channel[0]
Jul 21 11:45:56 em7-ca kernel: [18945.489531] <6>rgb133: DetectMode: NoVideo for dev[0].channel[0]
Jul 21 11:45:56 em7-ca kernel: [18945.512592] rgb133: AttemptDMAStart: Already an active buffer 
```

Galicaster goes into an error state and a subsequent capture does not start. Quitting and restarting Galicaster resolves the problem.

GC 2.x latest, Ubuntu 16.04, Datapath drivers:

[   12.357972] rgb133: rgb133_init: Datapath Ltd. - Vision Capture Driver ver 7.11.0.214 loaded ok.

presentation track (2 of them) like this:

```
[track1]
name = presentation
device = v4l2
flavor = presentation
location = /dev/dada0
file = presentation.avi
caps = video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720
active = True
```

**Comment by smarquard** [comment]
This seems to be related to the video input source changing (e.g. switching from a data projector to a document camera, etc.)

**Comment by smarquard** [comment]
We've tested with the latest beta driver from Datapath (7.11.0.215) and still get the problem.

**Comment by smarquard** [comment]
Datapath has released driver version 7.14.0.219 although it's not yet known whether this fixes the original problem.

Using io-mode=rw appears to work around the problem using earlier driver versions.

**Comment by smarquard** [comment]
Here is a pipeline which demonstrates the bug (without the io-mode workaround):

```
gst-launch-1.0 v4l2src device=/dev/dada0 ! video/x-raw,format=YUY2,framerate=25/1,width=1280,height=720 ! queue ! videorate ! videoconvert ! tee name=gc-v4l2-tee ! queue ! xvimagesink name=sink-presentation async=false qos=true sync=false force-aspect-ratio=true gc-v4l2-tee. ! queue ! valve drop=false name=gc-v4l2-valve ! videoconvert ! queue ! x264enc pass=5 quantizer=22 speed-preset=4 ! queue ! avimux ! queue ! filesink location=recording.avi async=false
```

It terminates with these errors after some switching of inputs:

```
0:00:44.133760212  4996      0x1f561e0 ERROR          v4l2allocator gstv4l2allocator.c:1299:gst_v4l2_allocator_dqbuf:<v4l2src0:pool:src:allocator> buffer 3 was not queued, this indicate a driver bug.
0:00:44.133779537  4996      0x1f561e0 WARN                 v4l2src gstv4l2src.c:884:gst_v4l2src_create:<v4l2src0> error: Failed to allocate a buffer
0:00:44.133819226  4996      0x1f561e0 WARN                 basesrc gstbasesrc.c:2948:gst_base_src_loop:<v4l2src0> error: Internal data flow error.
0:00:44.133824958  4996      0x1f561e0 WARN                 basesrc gstbasesrc.c:2948:gst_base_src_loop:<v4l2src0> error: streaming task paused, reason error (-5)
```

**Comment by smarquard** [comment]
Datapath has provided an experimental 7.14.0.223 driver which is believed to solve this issue.

It appears to work successfully on our test CA and we are now testing it in several production venues.

**Comment by smarquard** [comment]
I close this issue, as it is a driver problem rather than Galicaster issue, and appears to be fixed with the latest .223 Datapath driver.

**Comment by pmgration** [comment]
We've been experiencing this issue, but with Datapath Vision AV/B cards using the latest stable driver (`7.16.3.266`). We recently had the problem occur during a recording when the video pathway from a document camera couldn't stabilise (video kept dropping out and re-syncing), shortly before the recording stopped (due to the error) a message appeared on the captured video generated by the driver:

![datapath](https://user-images.githubusercontent.com/2735639/48096215-8f83d000-e20e-11e8-9cdf-7c7ab01b6345.png)

As per your previous messages (@smarquard), it seems to be Datapath driver related rather than Galicaster so adding to this issue for information only should anyone else experience this issue. For us it has so far been witnessed when using/after using a document camera - though we haven't been through all of the instances of this error occurring to conclusively determine that as a/the cause.

The `Changelog` file in the beta (`v7.17.14.304`) driver contains fixes relating to transitioning/selecting buffers, signal transition, memory leaks etc so we might give this a try at some point.

**Comment by pmgration** [comment]
Today we've managed to be able to reproduce the problem fairly reliably by constantly switching video signals into the capture card very quickly.
Upgraded the driver to the latest beta (`v7.17.14.304`) but this didn't resolve the issue.
We've since tried adding `io-mode = rw` to the v4l2 track for the Galicaster recording profile being used and haven't been able to reproduce the problem since..still testing but this is looking like the only solution so far!

**Comment by pmgration** [comment]
Thanks @smarquard

The only items added to the Changelog in `7.17.16.22055` since `7.17.14.304` are:

```
   30/08/2018 PG
 - Fix a bug which sometimes allowed erroneous channel open at driver initialisation (for example, at boot time).
 
   06/09/2018 PG
 - Add module load configurations and V4L2 controls for forcing the following colour domains: Full Range RGB BT.601, 
   Studio Range RGB BT.601, Full Range RGB BT.709, Studio Range RGB BT.709, Full Range RGB BT.2020, Studio Range RGB BT.2020, 
   Full Range YUV BT.601, Studio Range YUV BT.601, Full Range YUV BT.709, Studio Range YUV BT.709, Full Range YUV BT.2020, 
   Studio Range YUV BT.2020.
   Release 7.17.16
```

But we'll give it a go and see what happens

**Comment by pmgration** [comment]
We also found that a recording had been made with Galicaster this morning where we'd added `io-mode = rw` to the track and at the end of the recording Galicaster appeared to have crashed when the stop confirmation button was pressed - the recording metadata needed some manual intervention but it was all recoverable - we've disabled the `io-mode` option again for now
