### ISSUE TITLE
Video Flip for Webcameras

### ISSUE THREAD

**Issue by stefanosgeo** [teltek/Galicaster#62]
Hi,

In my university we need the ability to flip the camera image (due to camera position) either clockwise or counter clockwise. As a temporary solution, Teltek suggests to change the /galicaster/galicaster/recorder/bins and import the videoflip method = clockwise in pipest, like the following:

pipestr = (' v4l2src name=gc-v4l2-src ! capsfilter name=gc-v4l2-filter ! queue ! gc-v4l2-dec '
           ' videorate ! capsfilter name=gc-v4l2-vrate ! videocrop name=gc-v4l2-crop ! videoflip method=clockwise ! videoflip method=clockwise !'
           ' tee name=gc-v4l2-tee  ! queue !  xvimagesink async=false sync=false qos=false name=gc-v4l2-preview'
           ' gc-v4l2-tee. ! queue ! valve drop=false name=gc-v4l2-valve ! ffmpegcolorspace ! queue ! '
           ' gc-v4l2-enc ! queue ! gc-v4l2-mux ! '
           ' queue ! filesink name=gc-v4l2-sink async=false')

The parameter need to be set twice for upside down view.

We believe that will be very useful if the dev team imports this function in config file track fields, in a future release.

Regards

Stefanos Georgopoulos

**Comment by hcaloto** [comment]
Thanks stefanos for reporting this.

It looks like a pretty particular use case, and given the case that Galicaster can be tailored for each user needs thanks to the bin architecture having your own bin with those parameters added would be enough. Otherwise, adding an option for each and everyone of the video processing filters GStreamer has would be overkill and would add too much complexity to the already crowded profile configuration file.

**Comment by hcaloto** [comment]
As it solves a situation pretty common when you place a webcam reversed in a ceiling we've added this as an option, so you can add any filter before preview and encoder for v4l2 devices.
